DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS psa;

CREATE TABLE psa (
  ID  INTEGER PRIMARY KEY,
  PSA TEXT NOT NULL,
  TBL TEXT NOT NULL
);

CREATE TABLE jobs (
  ID  INTEGER PRIMARY KEY,
  PSA TEXT UNIQUE NOT NULL,
  NAM TEXT NOT NULL
);
